services:
  web:
    build: .
    ports:
      - "${HTTP_PORT:-3000}:3000"
    environment:
      HTTP_PORT: ${HTTP_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./:/app
    command: air -c .air.toml

networks:
  default:
    name: quadrant-network
    external: true